FROM cm2network/steamcmd:latest

ARG METAMOD_VERSION
ENV METAMOD_VERSION="${METAMOD_VERSION}"
ARG SOURCEMOD_VERSION
ENV SOURCEMOD_VERSION="${SOURCEMOD_VERSION}"

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
