on: [pull_request, push]

name: CI

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azohra/shell-linter@v0.4.0
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: ./build.sh
      - name: Log into Docker Hub
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u '${{ github.actor }}' --password-stdin
      - name: Build and push Docker image
        run: ./build.sh --push
